"""add_action_workflows

Revision ID: 23452711f18c
Revises: 278ed911dbab
Create Date: 2026-06-29 00:20:58.156245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '23452711f18c'
down_revision: Union[str, Sequence[str], None] = '278ed911dbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_action', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_workflows_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_workflows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_workflows_system_id'), ['system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_workflows_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_workflows_thread_id'))
        batch_op.drop_index(batch_op.f('ix_action_workflows_system_id'))
        batch_op.drop_index(batch_op.f('ix_action_workflows_status'))
        batch_op.drop_index(batch_op.f('ix_action_workflows_org_id'))

    op.drop_table('action_workflows')
    # ### end Alembic commands ###
